INSERT INTO BLOG(BLOG_ID, BLOG_NAME)
VALUES (1, 'kitty');

INSERT INTO BLOG(BLOG_ID, BLOG_NAME)
VALUES (2, 'animals');

INSERT INTO BLOG(BLOG_ID, BLOG_NAME)
VALUES (3, 'Deep Purple');

INSERT INTO POST (POST_ID, BLOG_NAME, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (1, 'kitty', 'Cute kitty', 123, '2018-01-01');
INSERT INTO POST (POST_ID, BLOG_NAME, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (2, 'kitty', 'Cute asdads', 3131, '2019-10-23');
INSERT INTO POST (POST_ID, BLOG_NAME, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (3, 'animals', 'Cute animals', 444, '2021-03-23');
INSERT INTO POST (POST_ID, BLOG_NAME, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (4, 'animals', 'Cute asdsda', 4454, '2021-03-23');
