INSERT INTO BLOG(BLOG_ID, BLOG_NAME)
VALUES (1, 'kitty');

INSERT INTO BLOG(BLOG_ID, BLOG_NAME)
VALUES (2, 'animals');

INSERT INTO BLOG(BLOG_ID, BLOG_NAME)
VALUES (3, 'Deep Purple');

INSERT INTO POST (POST_ID, BLOG_ID, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (1, 1, 'Cute kitty', 123, '2020-10-23');
INSERT INTO POST (POST_ID, BLOG_ID, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (2, 1, 'Cute asdads', 3131, '2020-10-23');
INSERT INTO POST (POST_ID, BLOG_ID, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (3, 2, 'Cute animals', 444, '2021-03-23');
INSERT INTO POST (POST_ID, BLOG_ID, TEXT, NUMBER_OF_LIKES, LOCAL_DATE)
VALUES (4, 2, 'Cute asdsda', 4454, '2021-03-23');
